import { db } from '../src/lib/db'

async function main() {
  const carriers = await Promise.all([
    db.shippingCarrier.create({
      data: {
        nameAr: 'البريد الليبي',
        nameEn: 'Libya Post',
        code: 'libya_post',
        type: 'national',
        phone: '+218 21 333 0000',
        email: 'info@libyapost.ly',
        website: 'https://www.libyapost.ly',
        trackingUrl: 'https://www.libyapost.ly/track/{trackingNumber}',
        basePrice: 5,
        pricePerKg: 1.0,
        maxWeight: 30,
        codFee: 1,
        codFixedFee: 2,
        estimatedDays: 5,
        isActive: true,
        isIntegrated: false,
        integrationType: 'manual',
        notes: 'الخدمة البريدية الوطنية - تغطي جميع المدن الليبية',
      },
    }),
    db.shippingCarrier.create({
      data: {
        nameAr: 'شركة النور للشحن',
        nameEn: 'Al Noor Shipping',
        code: 'alnoor',
        type: 'national',
        phone: '+218 91 234 5678',
        email: 'info@alnoorshipping.ly',
        website: 'https://www.alnoorshipping.ly',
        trackingUrl: 'https://www.alnoorshipping.ly/track/{trackingNumber}',
        apiEndpoint: 'https://api.alnoorshipping.ly/v1/shipments',
        basePrice: 7,
        pricePerKg: 1.5,
        maxWeight: 25,
        codFee: 1.5,
        codFixedFee: 3,
        estimatedDays: 3,
        isActive: true,
        isIntegrated: true,
        integrationType: 'api',
        notes: 'شركة شحن خاصة - تغطي المدن الكبرى مع API تكامل',
      },
    }),
    db.shippingCarrier.create({
      data: {
        nameAr: 'توصيل طرابلس',
        nameEn: 'Tripoli Express',
        code: 'tripoli_express',
        type: 'local',
        phone: '+218 92 555 1234',
        email: 'info@tripoliexpress.ly',
        website: 'https://www.tripoliexpress.ly',
        trackingUrl: 'https://www.tripoliexpress.ly/track/{trackingNumber}',
        basePrice: 3,
        pricePerKg: 0.5,
        maxWeight: 15,
        codFee: 0,
        codFixedFee: 1,
        estimatedDays: 1,
        isActive: true,
        isIntegrated: false,
        integrationType: 'manual',
        notes: 'خدمة توصيل محلية داخل طرابلس الكبرى - توصيل في نفس اليوم',
      },
    }),
    db.shippingCarrier.create({
      data: {
        nameAr: 'شركة الفاتح للنقل',
        nameEn: 'Al Fateh Transport',
        code: 'alfateh',
        type: 'national',
        phone: '+218 21 444 5555',
        email: 'info@alfatehtransport.ly',
        basePrice: 8,
        pricePerKg: 2.0,
        maxWeight: 50,
        codFee: 2,
        codFixedFee: 5,
        estimatedDays: 4,
        isActive: true,
        isIntegrated: false,
        integrationType: 'manual',
        notes: 'شركة نقل بري بين المدن الليبية - تتعامل مع الشحنات الثقيلة',
      },
    }),
    db.shippingCarrier.create({
      data: {
        nameAr: 'DHL ليبيا',
        nameEn: 'DHL Libya',
        code: 'dhl_libya',
        type: 'international',
        phone: '+218 21 335 0000',
        email: 'libya@dhl.com',
        website: 'https://www.dhl.com',
        trackingUrl: 'https://www.dhl.com/tracking?submit=1&tracking-id={trackingNumber}',
        apiEndpoint: 'https://api.dhl.com/track/shipments',
        basePrice: 25,
        pricePerKg: 5.0,
        maxWeight: 70,
        codFee: 0,
        codFixedFee: 0,
        estimatedDays: 7,
        isActive: true,
        isIntegrated: false,
        integrationType: 'api',
        notes: 'شحن دولي - تغطي أكثر من 220 دولة',
      },
    }),
    db.shippingCarrier.create({
      data: {
        nameAr: 'أرامكس ليبيا',
        nameEn: 'Aramex Libya',
        code: 'aramex_libya',
        type: 'international',
        phone: '+218 21 336 0000',
        email: 'libya@aramex.com',
        website: 'https://www.aramex.com',
        trackingUrl: 'https://www.aramex.com/track/results?ShipmentNumber={trackingNumber}',
        apiEndpoint: 'https://api.aramex.com/v1',
        basePrice: 20,
        pricePerKg: 4.0,
        maxWeight: 50,
        codFee: 2,
        codFixedFee: 5,
        estimatedDays: 5,
        isActive: true,
        isIntegrated: false,
        integrationType: 'api',
        notes: 'شحن دولي وإقليمي - مكاتب في طرابلس وبنغازي',
      },
    }),
  ])

  console.log(`✅ ${carriers.length} shipping carriers created`)
}

main()
  .catch(console.error)
  .finally(() => db.$disconnect())
